# Generated by Django 4.1.7 on 2023-06-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
